CREATE TABLE IF NOT EXISTS `master_mailer` (
  `id_user` int(11) NOT NULL auto_increment,
  `cust_num` varchar(25) default NULL,
  `name_formatted` varchar(255) default NULL,
  `name_family` varchar(64) default NULL,
  `name_given` varchar(64) default NULL,
  `name_additional` varchar(64) default NULL,
  `name_prefix` varchar(64) default NULL,
  `name_suffix` varchar(64) default NULL,
  `name_alternate` varchar(255) default NULL,
  `bday` varchar(10) default NULL,
  `gender` enum('M','F') NOT NULL default 'M',
  `email` varchar(255) default NULL,
  `email2` varchar(255) default NULL,
  `email3` varchar(255) default NULL,
  `addr_street1` varchar(255) default NULL,
  `addr_street2` varchar(255) default NULL,
  `addr_city` varchar(50) default NULL,
  `addr_state` varchar(32) default NULL,
  `addr_zip` varchar(15) default NULL,
  `addr_country` varchar(15) default NULL,
  `tel_pref` varchar(15) default NULL,
  `tel_home` varchar(15) default NULL,
  `tel_work` varchar(15) default NULL,
  `tel_ext` varchar(5) default NULL,
  `tel_fax` varchar(15) default NULL,
  `tel_cell` varchar(15) default NULL,
  `tel_pager` varchar(15) default NULL,
  `followup_email` enum('Y','N','') default NULL,
  `followup_mail` enum('Y','N','') default NULL,
  `followup_phone` enum('Y','N','') default NULL,
  `stock_num` varchar(20) default NULL,
  `year` varchar(4) default NULL,
  `make` varchar(25) default NULL,
  `model` varchar(25) default NULL,
  `serial_num` varchar(50) default NULL,
  `miles` varchar(7) default NULL,
  `activity_date` varchar(10) default NULL,
  `activity_num` varchar(25) default NULL,
  `note` text,
  PRIMARY KEY  (`id_user`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;